# .github/workflows/ci.yml
name: Simple Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Lint with flake8
        run: flake8 . --count --exit-zero --max-line-length=88 --statistics

      # ---- THIS IS THE FIX ----
      # Set the PYTHONPATH to the root of the project before running pytest
      - name: Run tests with pytest
        run: |
          export PYTHONPATH=.
          pytest