# .github/workflows/ci.yml
# This is a simple CI pipeline for a Python project

name: Simple Python CI

# Trigger the workflow on every push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up a specific version of Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install all required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install dependencies needed for running the code
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install dependencies needed for testing (pytest, flake8)
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      # Step 4: Download the spaCy model needed for tests
      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      # Step 5: Lint the code with flake8 to check for style issues
      - name: Lint with flake8
        run: flake8 . --count --exit-zero --max-line-length=88 --statistics

      # Step 6: Run the tests using pytest
      - name: Run tests with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest